### ISSUE TITLE
Integrating online-judge-template-generator

### ISSUE THREAD

**Issue by kmyk** [Saurav-Paul/AI-virtual-assistant-python#69]
I'm developing a tool to generate template codes and test cases generators.
It can generate input/output parts (e.g. `int n; std::cin >> n;`) for specified problems with reasonable accuracy. How about integrating this?

URL: https://github.com/online-judge-tools/template-generator
(sorry that now the readme is only Japanese...)

**Comment by Saurav-Paul** [comment]
Hey i will be happy to integrate that.. i have downloaded your module, it's like a magic... Like it....  I want to integrate it..

I have translated readme using google translator, not everything is clear... But i have understand most of the things.
